openapi: 3.0.3
info:
  title: NodeAPI @ Admin
  version: '1.0'
  description: Internal API for managing peers on vpn core nodes
  contact:
    name: Sergey Kovalev
    email: support@vpnhouse.net
paths:
  /api/tunnel/admin/peers:
    get:
      summary: Get list of peers
      operationId: admin-list-peers
      tags:
        - peers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PeerRecord'
        '401':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '403':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '500':
          $ref: 'common.yaml#/components/responses/ResponseError'
    post:
      summary: Create peer
      operationId: admin-create-peer
      tags:
        - peers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Peer'
      responses:
        '200':
          $ref: '#/components/responses/PeerInfo'
        '400':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '401':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '403':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '409':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '500':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '507':
          $ref: 'common.yaml#/components/responses/ResponseError'

  /api/tunnel/admin/peers/shared:
    post:
      summary: "create a peer for sharing via the unique link"
      operationId: "admin-create-shared-peer"
      tags:
        - peers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Peer'
      responses:
        '200':
          $ref: '#/components/responses/PeerLink'
        '400':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '401':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '403':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '409':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '500':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '507':
          $ref: 'common.yaml#/components/responses/ResponseError'


  '/api/tunnel/admin/peers/{id}':
    get:
      summary: Get peer info
      operationId: admin-get-peer
      tags:
        - peers
      responses:
        '200':
          $ref: '#/components/responses/PeerInfo'
        '401':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '403':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '404':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '500':
          $ref: 'common.yaml#/components/responses/ResponseError'
    put:
      summary: Update peer
      operationId: admin-update-peer
      tags:
        - peers
      responses:
        '200':
          $ref: '#/components/responses/PeerInfo'
        '400':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '401':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '403':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '404':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '409':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '500':
          $ref: 'common.yaml#/components/responses/ResponseError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Peer'

    delete:
      summary: Delete peer
      operationId: admin-delete-peer
      tags:
        - peers
      responses:
        '200':
          $ref: 'common.yaml#/components/responses/OperationSuccessful'
        '401':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '403':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '404':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '500':
          $ref: 'common.yaml#/components/responses/ResponseError'

    parameters:
      - schema:
          type: integer
          format: int64
          minimum: 1
          example: 42
        name: id
        in: path
        required: true

  /api/tunnel/admin/settings:
    get:
      summary: Get current server settings
      operationId: admin-get-settings
      tags:
        - settings
      responses:
        '200':
          $ref: '#/components/responses/SettingsInfo'
        '401':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '403':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '404':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '500':
          $ref: 'common.yaml#/components/responses/ResponseError'

    patch:
      summary: Update server settings
      operationId: admin-update-settings
      tags:
        - settings
      responses:
        '200':
          $ref: '#/components/responses/SettingsInfo'
        '400':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '401':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '403':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '500':
          $ref: 'common.yaml#/components/responses/ResponseError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Settings'

  /api/tunnel/admin/auth:
    get:
      summary: Authorize as the node admin
      operationId: admin-do-auth
      tags:
        - common
      responses:
        '200':
          $ref: '#/components/responses/AdminAuthResponse'
        '401':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '404':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '500':
          $ref: 'common.yaml#/components/responses/ResponseError'

      security:
        - Basic_auth: []
        - Token_auth: []

  /api/tunnel/admin/reload:
    get:
      summary: Reloads service with new configuration
      operationId: admin-reload-service
      tags:
        - common
      responses:
        '200':
          $ref: 'common.yaml#/components/responses/OperationSuccessful'
        '401':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '403':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '500':
          $ref: 'common.yaml#/components/responses/ResponseError'

  /api/tunnel/admin/status:
    get:
      summary: Get current service status
      operationId: admin-get-status
      tags:
        - common
      responses:
        '200':
          $ref: '#/components/responses/ServiceStatusResponse'
        '401':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '403':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '500':
          $ref: 'common.yaml#/components/responses/ResponseError'

  /api/tunnel/admin/initial-setup:
    post:
      summary: Set initial parameters
      operationId: admin-initial-setup
      tags:
        - settings
      # empty security because this handle must be public
      # (at least for the very first call).
      security: []
      responses:
        '200':
          $ref: 'common.yaml#/components/responses/OperationSuccessful'
        '400':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '401':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '403':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '409':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '500':
          $ref: 'common.yaml#/components/responses/ResponseError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InitialSetupRequest'

  '/api/tunnel/admin/connection-info/wireguard':
    get:
      operationId: admin-connection-info-wireguard
      summary: Get peer-independent wireguard configuration from a server
      tags:
        - connection-info
      responses:
        '200':
          $ref: '#/components/responses/ServerWireguardOptions'
        '401':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '409':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '500':
          $ref: 'common.yaml#/components/responses/ResponseError'

  '/api/tunnel/admin/ip-pool/suggest':
    get:
      summary: Suggest an available IP address by the server pool
      operationId: admin-ippool-suggest
      tags:
        - ippool
      responses:
        '200':
          $ref: '#/components/responses/IpPoolSuggestResult'
        '404':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '409':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '500':
          $ref: 'common.yaml#/components/responses/ResponseError'
    post:
      operationId: admin-ippool-is-used
      summary: Check that the IP address is used by the server pool
      tags:
        - ippool
      responses:
        '200':
          $ref: 'common.yaml#/components/responses/OperationSuccessful'
        '404':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '409':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '500':
          $ref: 'common.yaml#/components/responses/ResponseError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IpPoolAddress'

  '/api/tunnel/public/activate-peer/{key}':
    parameters:
      - schema:
          type: string
        name: key
        in: path
        required: true
    get:
      operationId: public-peer-status
      summary: Chech the shared peer status before the activation request
      tags:
        - shared-peer
      responses:
        '200':
          $ref: '#/components/responses/PeerActivationStatus'
        '404':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '409':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '500':
          $ref: 'common.yaml#/components/responses/ResponseError'
    post:
      operationId: public-peer-activate
      summary: Activate the shared peer via the unique URL
      tags:
        - shared-peer
      responses:
        '200':
          $ref: '#/components/responses/PeerActivationResponse'
        '404':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '409':
          $ref: 'common.yaml#/components/responses/ResponseError'
        '500':
          $ref: 'common.yaml#/components/responses/ResponseError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'tunnel.yaml#/components/schemas/PeerWireguard'

components:
  schemas:
    Settings:
      title: Settings
      type: object
      x-examples:
        example-read:
          value:
            wireguard_listen_port: 3000
            wireguard_keepalive: 60
            wireguard_subnet: 10.42.0.0/16
            wireguard_server_ipv4: 1.2.3.4
            wireguard_server_port: 3000
            wireguard_public_key: n4btQ30d0OxK12rIzbN5mWk2MGZm8EWxrrk6LFro320=
            ping_interval: 300
            connection_timeout: 600
            http_listen_addr: '0.0.0.0:80'
            dns:
              - 192.168.0.1
        example-write:
          value:
            log_level: debug
            admin_password: My$uperp@$$@0rd
            wireguard_listen_port: 3000
            wireguard_keepalive: 60
            wireguard_subnet: 10.42.0.0/16
            wireguard_server_ipv4: 1.2.3.4
            wireguard_server_port: 3000
            ping_interval: 300
            connection_timeout: 600
            http_listen_addr: '0.0.0.0:80'
            dns:
              - 192.168.0.1
      description: Server-side configuration.
      properties:
        admin_password:
          type: string
          format: password
          description: 'Admin password (write-only, never returned).'
          example: My$uperp@$$@0rd
          writeOnly: true
        wireguard_listen_port:
          type: integer
          minimum: 1
          maximum: 65535
          example: 3000
          description: |
            Wireguard listen port inside the container.
            In 99% cases it matches the `wireguard_server_port` value.
        wireguard_server_port:
          type: integer
          minimum: 1
          maximum: 65535
          example: 3000
          description: |
            Public UDP port of a wireguard server.
            This value is announced to peers, in 99% cases it is the same as the `wireguard_listen_port`.
            May differs from the `wireguard_listen_port`'s value if NATed (especially with docker).
        wireguard_keepalive:
          type: integer
          minimum: 1
          example: 60
          description: Keepalive interval for wireguard peers.
        wireguard_subnet:
          type: string
          example: 10.42.0.0/16
          description: Subnet for wireguard peers.
        wireguard_server_ipv4:
          type: string
          example: 1.2.3.4
          format: ipv4
          description: Public ipv4 address of a wireguard server.
        wireguard_public_key:
          type: string
          example: n4btQ30d0OxK12rIzbN5mWk2MGZm8EWxrrk6LFro320=
          minLength: 44
          maxLength: 44
          description: Wireguard public key (read only).
          readOnly: true
        ping_interval:
          type: integer
          example: 300
          minimum: 1
        connection_timeout:
          type: integer
          example: 600
          minimum: 1
        http_listen_addr:
          type: string
          example: '0.0.0.0:80'
          description: 'HTTP listening IP:Port pair.'
        dns:
          type: array
          description: DNS servers to announce to a peer
          items:
            type: string
            format: ipv4
        domain:
          # optional domain+SSL config,
          # send this if "[ ] I have a domain" is checked.
          $ref: "#/components/schemas/DomainConfig"
        send_stats:
          description: allow to send anonymous hearbeats
          type: boolean
    AdminAuth:
      title: ResponseAdminAuth
      type: object
      properties:
        access_token:
          type: string
          description: JWT for accessing other administrative endpoints.
          readOnly: true
      required:
        - access_token
    ProtocolStats:
      title: ProtocolStats
      type: object
      description: Represents traffic and peer stats for specific protocol
      properties:
        peers_total:
          type: integer
          description: 'Totally allocated peers for protocol'
        peers_active:
          type: integer
          description: 'Recently active peers count'
        traffic_up:
          type: integer
          format: int64
          description: 'Upstream traffc accross all peers in bytes'
        traffic_down:
          type: integer
          format: int64
          description: 'Downstream traffic accross all peers in bytes'
        speed_up:
          type: integer
          format: int64
          description: 'Upload speed accross all peers in bytes per second'
        speed_down:
          type: integer
          format: int64
          description: 'Download speed accross all peers in bytes per second'
    ServiceStatus:
      title: ServiceStatusResponse
      type: object
      description: Holds current staus flags of the service
      properties:
        restart_required:
          type: boolean
          description: 'Indicate, whether service requires restart to apply latest settings.'
        stats_global:
          $ref: '#/components/schemas/ProtocolStats'
        stats_wireguard:
          $ref: '#/components/schemas/ProtocolStats'
        stats_iprose:
          $ref: '#/components/schemas/ProtocolStats'
        stats_proxy:
          $ref: '#/components/schemas/ProtocolStats'
      required:
        - restart_required
    Peer:
      type: object
      title: Peer
      description: Peer representation.
      x-examples:
        example:
          value:
            id: 42
            label: Home PC
            info_wireguard:
              public_key: ljs1lRH1YtZPlppYl1gQVX+JTNmTQsX57cIDf7oB6Qc=
            ipv4: 10.42.3.33
            created: '2021-05-28T13:23:15Z'
            updated: '2021-05-28T13:23:15Z'
            expires: '2021-05-28T13:43:10Z'
            peer_id: 46a6dbb2-1cc6-48e7-8374-0d386c3f17f0
            claims: string
      properties:
        label:
          type: string
          description: Label of the peer.
          example: Home PC
          nullable: true
        info_wireguard:
          $ref: 'tunnel.yaml#/components/schemas/PeerWireguard'
        identifiers:
          $ref: 'common.yaml#/components/schemas/ConnectionIdentifiers'
        claims:
          type: string
          description: JWT information data.
          nullable: true
        ipv4:
          type: string
          format: ipv4
          description: Tunneling IPv4 address of a peer.
          example: 10.42.3.33
          nullable: true
        net_access_policy:
          description: |
            Network policy: isolate the peer (internet access only)
            or allow to talk to its network neighbours (like in LANs)
          type: integer
          enum:
            - 0
            - 1
            - 2
          x-enum-varnames:
            - Default
            - InternetOnly
            - AllowAll
          nullable: true
        rate_limit:
          description: |
            How much of bandwidth the client is allowed to consume.
            Takes no effect if the traffic control subsystem is
            disabled on a node.
            [!] Bits per Second, must follow SI.
          type: integer
          nullable: true
        expires:
          type: string
          format: date-time
          example: '2021-05-28T13:43:10Z'
          description: Peer expiration time.
          nullable: true
        created:
          type: string
          format: date-time
          description: The date when the peer was created.
          example: '2021-05-28T13:23:15Z'
        updated:
          type: string
          format: date-time
          description: The date when the peer was updated last time.
          example: '2021-05-28T13:23:15Z'
        activity:
          type: string
          format: date-time
          description: Last date the peer had traffic activity.
          example: '2021-05-28T13:23:15Z'
        traffic_up:
          type: integer
          format: int64
          description: 'Peer upload traffic in bytes'
        traffic_down:
          type: integer
          format: int64
          description: 'Peer download traffic in bytes'
        traffic_up_speed:
          type: integer
          format: int64
          description: 'Peer upload speed in bytes per second'
        traffic_down_speed:
          type: integer
          format: int64
          description: 'Peer download speed in bytes per second'
    PeerRecord:
      title: Peer repr for a list responses
      type: object
      example:
        id: 42
        peer:
          label: Home PC
          type: wireguard
          info_wireguard:
            public_key: ljs1lRH1YtZPlppYl1gQVX+JTNmTQsX57cIDf7oB6Qc=
          identifiers:
            user_id: Project/Authorizer/user@org
            installation_id: d1a1b2e2-d84b-4537-9a93-c4d3cd412598
            session_id: de9e0337-fb16-4669-b07d-9f261c329461
          claims: string
          ipv4: 10.42.3.33
          expires: '2021-05-28T13:43:10Z'
          created: '2021-05-28T13:23:15Z'
          updated: '2021-05-28T13:23:15Z'
          activity: '2021-05-28T13:23:15Z'
          traffic_up: 123404321
          traffic_down: 896123404321
          traffic_up_speed: 1234560
          traffic_down_speed: 0
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
          example: 42
        peer:
          $ref: '#/components/schemas/Peer'
      required:
        - id
        - peer
    InitialSetupRequest:
      title: initial setup request
      type: object
      properties:
        admin_password:
          type: string
        server_ip_mask:
          type: string
        send_stats:
          description: allow to send anonymous hearbeats and install notifications
          type: boolean
        domain:
          # optional domain name config,
          # send this if "[ ] I have a domain" is checked.
          $ref: "#/components/schemas/DomainConfig"
      required:
        - admin_password
        - server_ip_mask
    DomainConfig:
      description: |
        Domain name, reverse proxy, and SSL configuration,
        used for the initial configuration.
      type: object
      properties:
        mode:
          description: |
            Shows how the http traffic delivered to the service.
            The "direct" meand that we serve 80/443 by ourselves, so
            we can also manage the SSL certificates.
            The "reverse-proxy" means that we're behind the reverse proxy,
            like nginx. We wont manage and serve the SSL traffic in that case.
          type: string
          enum: ["direct", "reverse-proxy"]
        domain_name:
          description: |
            Domain name for the service, required.
            In the "direct" mode we'll issue the SSL certificate for that domain name,
            in "reverse-proxy" mode we need this name to build the extenral links.
            If no configuraton is provided (InitialSetupRequest->domain is empty) - the external IP is used.
          type: string
        issue_ssl:
          description: |
            We'll try to issue the SSL certificate if set.
            For the "direct" mode only.
          type: boolean
        schema:
          description: |
            How the reverse-proxy serving our traffic for the external clients.
            So the schema + domain_name produces a valid link to the service.
            For the "reverse-proxy" mode only.
          type: string
          enum: ["http", "https"]
      required:
        - mode
        - domain_name
        - issue_ssl
        - schema

    IpPoolAddress:
      title: ""
      properties:
        ip_address:
          type: string
      required:
        - ip_address

    WireguardOptions:
      description: Peer-independent wireguard configuration from a server
      type: object
      properties:
        subnet:
          description: "Network subnet/mask for wireguard clients, e.g 10.235.0.0/24"
          type: string
        server_public_key:
          type: string
          minLength: 44
          maxLength: 44
          example: b0o7b8vXx9EH3uLJucOJUed0slvSppv7RCmC8jXRr1o=
          description: Server public key.
        server_ipv4:
          type: string
          format: ipv4
          example: 1.2.3.4
          description: Public IPv4 of a wireguard server.
        server_port:
          type: integer
          minimum: 1
          maximum: 65535
          example: 3000
          description: Public wireguard port.
        keepalive:
          type: integer
          minimum: 0
          maximum: 3600
          example: 60
          description: Keepalive interval to be set on client side.
        allowed_ips:
          type: array
          description: 'List of subnets, allowed to be sent to tunnel.'
          items:
            type: string
            example: 0.0.0.0/0
        dns:
          type: array
          description: List of DNS servers.
          items:
            type: string
            format: ipv4
      required:
        - server_public_key
        - server_ipv4
        - server_port
        - keepalive
        - allowed_ips
        - dns
        - subnet

    PeerActivation:
      description: |
        Returns the status of the shared peer.
        "not_activated" - no configuration has been given, we can
          activate it immeadietly.
        "activated" - the peer has already been activated,
          we must ask a user about a re-activation (previously
          issued credentials will be invalidated).
      type: object
      properties:
        status:
          type: string
          enum: [ "not_activated", "activated" ]
      required:
        - status

  responses:
    PeerInfo:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Peer'
    PeerLink:
      description: "A link to activate the shared peer"
      content:
        application/json:
          schema:
            type: object
            properties:
              link:
                type: string
            required:
              - link
    PeerActivationResponse:
      description: |
        Full information about the Wireguard connection
        for the activated peer. Used to build QR code and config
        on the publicly available activation page.
      content:
        application/json:
          schema:
            type: object
            properties:
              peer:
                $ref: '#/components/schemas/PeerRecord'
              wireguard_options:
                $ref: '#/components/schemas/WireguardOptions'
            required:
              - peer
              - wireguard_options
    PeerActivationStatus:
      description: ""
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PeerActivation'
    SettingsInfo:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Settings'
    ServerWireguardOptions:
      description: Peer-independent wireguard configuration from a server
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WireguardOptions'
    IpPoolSuggestResult:
      description: returns suggested IP address
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/IpPoolAddress'
    AdminAuthResponse:
      description: return credentials of authorized session
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AdminAuth'
    ServiceStatusResponse:
      description: "returns current status flags"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ServiceStatus'

  securitySchemes:
    Token_auth:
      type: http
      scheme: bearer
    Basic_auth:
      type: http
      scheme: basic

security:
  - Token_auth: []
